### ISSUE TITLE
Client status string not overridden from the command line

### ISSUE THREAD

**Issue by awarnock3** [clustericious/Clustericious#19]
I can start the server on a different port than the one listed in the config file using "-l" (e.g., "perl -Ilib bin/restapp daemon -l http://\*:9001") and although it's *listening* on 9001, it responds to "restappclient status" saying it's running on whatever port is specified in the config file. If the port is passed in from the command line via "-l", the response to the status request probably ought to reflect that.

**Comment by plicease** [comment]
@awarnock3 `/status` now returns a URL with a trailing slash, which caused a couple of tests in Yars to fail.  This behavior is arguably more consistent, so I am going to keep it, but keep an eye out for similar failing tests.

**Comment by awarnock3** [comment]
Fine by me.
