### ISSUE TITLE
config_with_filename.t fails on Windows

### ISSUE THREAD

**Issue by chorny** [clustericious/Clustericious#23]
due to this eval:
```
# line 141 "C:\Strawberry201\cpan\build\Clustericious-1.06-8c6DRi\blib\lib/Clustericious/Config.pm"
@Clustericious::Config::App::cwd::C:::DOCUME::c::LOCALS::Temp::rktZwMT_A::Foo::ISA = ('Clustericious::Config')
```
Note 3 ':' after 'cwd::C', Windows paths start with drive letter and ':' after it.

**Comment by plicease** [comment]
Can you check if that fixes it?  My windows machine is borked right now and I am unable to test it myself.

**Comment by plicease** [comment]
I was able to get into my windows machine afterall and verified the fix, so I am closing.  Please reopen if you find elsewise.

Thanks for the report!
